language: python
python: "3.6"

sudo: false

services:
  - docker
  - postgresql

install:
  - docker-compose up -d

postgres:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - docker-compose exec django sh -c "coverage run ceiphr_proj/manage.py test --settings=ceiphr.settings.ci"

deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master

after_success:
  - docker-compose exec django sh -c "codecov"