language: python
python: "3.6"

sudo: false

services:
- docker
- postgresql

# install:
# - docker-compose pull
# - docker-compose build
# - pip install -r requirements.txt
# - pip install .

postgres:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - coverage run ceiphr_proj/manage.py test --settings=ceiphr.settings.ci

after_success:
- codecov