language: python
python: "3.6"

sudo: false

services:
- docker
- postgresql

# before_install:
#   - docker-compose build -t ceiphr/ceiphr.com .
#   - docker run -d -p 127.0.0.1:80:4567 ceiphr/ceiphr.com /bin/sh -c "cd /root/ceiphr.com; bundle exec foreman start;"
#   - docker ps -a
#   - docker run ceiphr/ceiphr.com /bin/sh -c "cd /root/ceiphr.com; bundle exec rake test"

install:
- docker-compose build
- docker-compose up

postgres:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - coverage run ceiphr_proj/manage.py test --settings=ceiphr.settings.ci

after_success:
- codecov