language: python
python: "3.6"

sudo: false

services:
  - docker
  - postgresql

# Ensuring docker build works
install:
  - docker-compose up -d
  - pip install -r requirements.txt

postgres:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  # TODO Set up codecov within docker container
  # https://docs.codecov.io/docs/testing-with-docker
  # - docker-compose exec django sh -e ci_env="bash <(curl -s https://codecov.io/env)" -c "coverage run ceiphr_proj/manage.py test --settings=ceiphr.settings.ci"
  - coverage run ceiphr_proj/manage.py test --settings=ceiphr.settings.ci

deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master

after_success:
  # - bash <(curl -s https://codecov.io/bash)
  - codecov
