language: python
python: "3.6"

sudo: false

services:
  - docker
  - postgresql

# Ensuring docker build works
install:
  - docker-compose up -d

postgres:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - docker-compose run --no-deps --rm web python3 manage.py test

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
