version: "3.3"

services:
  web:
    container_name: ceiphr.com
    image: ceiphr/ceiphr.com
    environment:
      - DEBUG=1
      - ADMIN_ENABLED=1
    build:
      context: .
      dockerfile: ceiphr_proj/Dockerfile
      args:
        BUILD_DATE: date -u +'%Y-%m-%dT%H:%M:%SZ'
        VCS_REF : git rev-parse origin/master
    command: python3 /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ceiphr_proj/:/usr/src/app/
    ports:
      - "8000:8000"
