version: "3.3"

services:

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html \
      --email contact@ceiphr.com --agree-tos --no-eff-email -d staging.ceiphr.com  #-d www.example.com

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  django:
    build: .
    restart: unless-stopped
    container_name: ceiphrcom
    env_file:
      - .env
    command: gunicorn --bind 0.0.0.0:8080 ceiphr.wsgi
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
    - django-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ari/ceiphr.com/ceiphr_proj/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ari/ceiphr.com/dhparam/
      o: bind

networks:
  django-network:
    driver: bridge
