version: '3.3'

services:
  db:
    image: postgres

  django:
    container_name: ceiphr.com
    image: ceiphr/ceiphr.com
    env_file:
      - .env
    environment:
      - DEBUG=1
      - ADMIN_ENABLED=1
    build: .
    command: python3 /ceiphrcom/ceiphr_proj/manage.py runserver 0.0.0.0:8000 --settings=ceiphr.settings.development
    volumes:
      - .:/ceiphrcom
    ports:
      - "8000:8000"
    depends_on:
      - db
