version: '3'

services:
  db:
    image: postgres
  django:
    build: .
    command: >
      bash -c '
      python ceiphr_proj/manage.py collectstatic --no-input &&
      python ceiphr_proj/manage.py runserver 0.0.0.0:8000 --settings=ceiphr.settings.development'
    volumes:
      - .:/ceiphrcom
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    build: .
    image: app
    command: >
      bash -c '
        python ceiphr_proj/manage.py makemigrations &&
        python ceiphr_proj/manage.py migrate'
    volumes:
      - .:/ceiphrcom
    links:
      - db
    depends_on:
      - db
