version: '3'

services:
  db:
    image: postgres

  django:
    container_name: ceiphr.com
    image: ceiphr/ceiphr.com
    build: .
    command: >
      /bin/sh -c '
        python3 /ceiphrcom/ceiphr_proj/manage.py runserver 0.0.0.0:8000 --settings=ceiphr.settings.development &&
        python3 /ceiphrcom/ceiphr_proj/manage.py makemigrations &&
        python3 /ceiphrcom/ceiphr_proj/manage.py migrate'
    volumes:
      - .:/ceiphrcom
    ports:
      - "8000:8000"
    depends_on:
      - db
