version: "3.3"

services:

  nginx:
    build: ./nginx
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 1337:80
      - 80:80
      - 443:443
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    image: postgres:alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ceiphrcom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - DATABASE=postgres
    ports:
      - "5432:5432"

  web:
    build: 
      context: .
      dockerfile: ceiphr_proj/Dockerfile.prod
    restart: unless-stopped
    container_name: ceiphrcom
    env_file: .env
    command: gunicorn ceiphr.wsgi:application --bind 0.0.0.0:8000
    expose:
    - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./ceiphrcom/:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    environment: 
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=ceiphrcom
      - SQL_USER=postgres
      - SQL_PASSWORD=$SQL_PASSWORD
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
    links:
      - db:db

volumes:
  postgres_data:
  static_volume:
  media_volume:
