version: "3.3"

services:
  web:
    container_name: ceiphr.com
    image: ceiphr/ceiphr.com
    environment: 
      SECRET_KEY: change_me
    build:
      context: .
      dockerfile: ceiphr_proj/Dockerfile
      args:
        BUILD_DATE: date -u +'%Y-%m-%dT%H:%M:%SZ'
        VCS_REF : git rev-parse origin/master
    command: python3 /usr/src/app/ceiphr_proj/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
