version: "3.3"

services:
  web:
    container_name: ceiphr.com
    image: ceiphr/ceiphr.com
    environment:
      - DEBUG=1
      - ADMIN_ENABLED=1
    build:
      context: .
      dockerfile: ceiphr_proj/Dockerfile
    command: python3 /ceiphrcom/ceiphr_proj/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ceiphrcom/:/usr/src/app/
    ports:
      - "8000:8000"
