version: '3'

services:
  db:
    image: postgres
  django:
    build: .
    command: python3 /ceiphrcom/ceiphr_proj/manage.py runserver 0.0.0.0:8000 --settings=ceiphr.settings.development
    volumes:
      - .:/ceiphrcom
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    build: .
    image: app
    command: >
      /bin/sh -c '
        python3 /ceiphrcom/ceiphr_proj/manage.py makemigrations &&
        python3 /ceiphrcom/ceiphr_proj/manage.py migrate'
    volumes:
      - .:/ceiphrcom
    links:
      - db
    depends_on:
      - db
