version: "3.3"

services:

  nginx:
    build: ./nginx
    env_file: .env
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  web:
    build: 
      context: .
      dockerfile: ceiphr_proj/Dockerfile.prod
    env_file: .env
    restart: unless-stopped
    container_name: ceiphrcom
    command: gunicorn ceiphr.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./ceiphr_proj/:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    environment: 
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=ceiphrcom
      - SQL_USER=postgres
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ceiphrcom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume:
